### ISSUE TITLE
port conflicts when using joblib.Parallel or multiprocessing

### ISSUE THREAD

**Issue by shiodat** [jubatus/jubakit#44] opened 2016-08-15 04:24 UTC
When I tried to launch several jubatus servers using joblib.Parallel, 
jubakit sometimes get ports that already got by joblib.Parallel and job stopped.

For example, the problem occurs when using scikit-learn.grid.GridSearchCV with parallel settings.
https://gist.github.com/shiodat/57d74827dbffd726a814cc280196c5be

**Comment by kmaehashi** [comment] 2016-08-16 04:58
There is a lag between detecting free port number (done by jubakit) and actually binding to the port (done by jubatus server processes).  By design we cannot prevent this completely.  So we decided to workaround this issue by:

* randomly assign port number, instead of sequentially assign from 10000
* retry 10 times if server failed to start

**Comment by kmaehashi** [comment] 2016-08-30 05:27
Fixed via #54

**Closed by kmaehashi** 2016-08-30 05:27 UTC
